### ISSUE TITLE
Session warnings

### ISSUE THREAD

**Issue by R-N** [nguyenanhung/codeigniter3-vercel-skeleton#7]
I'm getting a lot of session warnings.

- `ini_set(): Session ini settings cannot be changed after headers have already been sent`
- `session_set_cookie_params(): Session cookie parameters cannot be changed after headers have already been sent`
- `session_set_save_handler(): Session save handler cannot be changed after headers have already been sent`
- `session_start(): Session cannot be started after headers have already been sent`

None of them shows when run locally. And session_start is only called once, in the Session library. Nowhere else. 

How do I fix this? Or maybe I should just ignore them? 
Or maybe Session is just not supported when running on Vercel?

**Comment by nguyenanhung** [comment]
@R-N You should debug by testing, instead of just looking at the error message and assessing the problem

Check where the session file is saved via phpinfo, and remind if you forget, codeigniter has a configuration to store the session right inside the application (session_save_path in config.php file)

Anything, should be tested, reproduced.

**Comment by R-N** [comment]
Ok so a session header was sent because something was being output-ed early. A warning during database initialization (the quotation mark thing). Resolving that also resolves the session warnings. Closing.
